export const CANVAS_CONFIG = {
  ZOOM: {
    MIN_SCALE: 0.1,
    MAX_SCALE: 5,
    SCALE_FACTOR: 1.02
  },
  SHAPES: {
    DEFAULT_FILL: '#3b82f6',
    CIRCLE_RADIUS: 30,
    RECT_SIZE: 60,
    STAR_INNER_RADIUS: 20,
    STAR_OUTER_RADIUS: 30,
    STAR_POINTS: 5
  },
  SELECTION: {
    BORDER_COLOR: '#ef4444',
    BORDER_WIDTH: 2,
    BORDER_DASH: [5, 5],
    DELETE_BUTTON_RADIUS: 12,
    DELETE_BUTTON_COLOR: '#ef4444',
    DELETE_BUTTON_STROKE: 'white',
    DELETE_BUTTON_STROKE_WIDTH: 2,
    BORDER_OFFSET: 5,
    BORDER_SIZE: 70
  }
};